name: Build PS4 FPKG

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout project files
      uses: actions/checkout@v4

    # الخطوة الأولى: تجهيز مجلد نظيف وترتيب الملفات الخاصة بالسوني
    - name: Prepare Clean Package Folder
      run: |
        mkdir staging
        mkdir staging/sce_sys
        if (Test-Path "sce_sys") { cp sce_sys/* staging/sce_sys/ }
        if (Test-Path "icon0.png") { cp icon0.png staging/sce_sys/ }
        if (Test-Path "downloads.json") { cp downloads.json staging/ }
        if (Test-Path "src") { cp -r src staging/ }

    # الخطوة الثانية: تشغيل أداة التجميع التي رفعتها أنت في مجلد tools
    - name: Compile Fake PKG
      run: |
        ./tools/orbis-pub-cmd.exe img_create "./staging/sce_sys/param.sfo" "./output.pkg"
      continue-on-error: true

    # الخطوة الثالثة: حفظ ورفع ملف البكج النهائي لتستطيع تحميله
    - name: Upload Finished PKG
      uses: actions/upload-artifact@v4
      with:
        name: PS4-Executable-PKG
        path: ./*.pkg
